version: "3.8"

services:
  # PostgreSQL - Hive Metastore Database
  postgres:
    image: postgres:14-alpine
    container_name: hadoop-postgres
    environment:
      POSTGRES_DB: metastore
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - hadoop-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hive"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Hadoop NameNode (HDFS Master)
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: hadoop-namenode
    hostname: namenode
    environment:
      - CLUSTER_NAME=hadoop-cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - CORE_CONF_hadoop_http_staticuser_user=root
      - HDFS_CONF_dfs_webhdfs_enabled=true
      - HDFS_CONF_dfs_permissions_enabled=false
      - HDFS_CONF_dfs_replication=1
    ports:
      - "9870:9870"  # NameNode Web UI
      - "9000:9000"  # HDFS port
    volumes:
      - namenode-data:/hadoop/dfs/name
      - ./src:/project/src
      - ./input:/project/input
    networks:
      - hadoop-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9870/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Hadoop DataNode (HDFS Worker)
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: hadoop-datanode
    hostname: datanode
    environment:
      - SERVICE_PRECONDITION=namenode:9870
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_replication=1
    ports:
      - "9864:9864"  # DataNode Web UI
    volumes:
      - datanode-data:/hadoop/dfs/data
    networks:
      - hadoop-network
    depends_on:
      - namenode

  # Hadoop ResourceManager (YARN Master)
  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: hadoop-resourcemanager
    hostname: resourcemanager
    environment:
      - SERVICE_PRECONDITION=namenode:9000 namenode:9870 datanode:9864
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - YARN_CONF_yarn_log___aggregation___enable=true
      - YARN_CONF_yarn_resourcemanager_recovery_enabled=true
      - YARN_CONF_yarn_resourcemanager_store_class=org.apache.hadoop.yarn.server.resourcemanager.recovery.FileSystemRMStateStore
      - YARN_CONF_yarn_resourcemanager_fs_state___store_uri=/rmstate
      - YARN_CONF_yarn_nodemanager_remote___app___log___dir=/app-logs
      - YARN_CONF_yarn_log_server_url=http://historyserver:8188/applicationhistory/logs/
      - YARN_CONF_yarn_timeline___service_enabled=true
      - YARN_CONF_yarn_timeline___service_generic___application___history_enabled=true
      - YARN_CONF_yarn_resourcemanager_system___metrics___publisher_enabled=true
      - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
      - YARN_CONF_yarn_timeline___service_hostname=historyserver
      - YARN_CONF_yarn_resourcemanager_address=resourcemanager:8032
      - YARN_CONF_yarn_resourcemanager_scheduler_address=resourcemanager:8030
      - YARN_CONF_yarn_resourcemanager_resource__tracker_address=resourcemanager:8031
    ports:
      - "8088:8088"  # ResourceManager Web UI
    volumes:
      - resourcemanager-data:/rmstate
    networks:
      - hadoop-network
    depends_on:
      - namenode
      - datanode

  # Hadoop NodeManager (YARN Worker)
  nodemanager:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: hadoop-nodemanager
    hostname: nodemanager
    environment:
      - SERVICE_PRECONDITION=namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
      - YARN_CONF_yarn_resourcemanager_address=resourcemanager:8032
      - YARN_CONF_yarn_resourcemanager_scheduler_address=resourcemanager:8030
      - YARN_CONF_yarn_resourcemanager_resource__tracker_address=resourcemanager:8031
      - YARN_CONF_yarn_nodemanager_aux___services=mapreduce_shuffle
      - YARN_CONF_yarn_nodemanager_resource_memory___mb=4096
      - YARN_CONF_yarn_nodemanager_resource_cpu___vcores=2
    ports:
      - "8042:8042"  # NodeManager Web UI
    volumes:
      - nodemanager-data:/hadoop/yarn/local
    networks:
      - hadoop-network
    depends_on:
      - namenode
      - datanode
      - resourcemanager

  # Hadoop History Server
  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
    container_name: hadoop-historyserver
    hostname: historyserver
    environment:
      - SERVICE_PRECONDITION=namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    ports:
      - "8188:8188"  # History Server Web UI
    volumes:
      - historyserver-data:/hadoop/yarn/timeline
    networks:
      - hadoop-network
    depends_on:
      - namenode
      - datanode
      - resourcemanager

  # Hive Metastore
  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hadoop-hive-metastore
    hostname: hive-metastore
    environment:
      - SERVICE_PRECONDITION=namenode:9870 datanode:9864 postgres:5432
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    command: /opt/hive/bin/hive --service metastore
    ports:
      - "9083:9083"
    networks:
      - hadoop-network
    depends_on:
      - postgres
      - namenode
      - datanode

  # Hive Server2 (z Beeline)
  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hadoop-hive-server
    hostname: hive-server
    environment:
      - SERVICE_PRECONDITION=hive-metastore:9083 namenode:9870 datanode:9864
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HIVE_CORE_CONF_javax_jdo_option_ConnectionURL=jdbc:postgresql://postgres:5432/metastore
      - HIVE_CORE_CONF_javax_jdo_option_ConnectionDriverName=org.postgresql.Driver
      - HIVE_CORE_CONF_javax_jdo_option_ConnectionUserName=hive
      - HIVE_CORE_CONF_javax_jdo_option_ConnectionPassword=hive
    ports:
      - "10000:10000"  # HiveServer2 (Beeline)
      - "10002:10002"  # HiveServer2 Web UI
    volumes:
      - ./src:/project/src
      - ./input:/project/input
    networks:
      - hadoop-network
    depends_on:
      - hive-metastore
      - namenode
      - datanode

networks:
  hadoop-network:
    driver: bridge

volumes:
  postgres-data:
  namenode-data:
  datanode-data:
  resourcemanager-data:
  nodemanager-data:
  historyserver-data:
